baseURL = "https://wch.ink/"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-cn"
title = "王长号的博客"
copyright = "This is a customized copyright."
theme = "diary"
# googleAnalytics = "UA-123-45"


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "记录美好的每一天."
enableGitalk = false
enableGiscus = true
hideCopyright = true


# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
clarity = "abcdefghzd"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "王长号的博客"
description = "王长号的博客"


# Please visit https://giscus.app/ to generate settings.
[params.giscus]
    data_repo="wang-c-h/blog"
    data-repo-id="R_kgDOJv1xHA"    
    data_category="Comment"
    data_category_id="DIC_kwDOJv1xHM4CXPBF"
    data_mapping="pathname"
    data_strict="0"
    data_reactions_enabled="1"
    data_emit_metadata="1"
    data_input_position="bottom"
    data_theme="preferred_color_scheme"
    data-lang="zh-CN"
    data-loading="lazy"
    crossorigin="anonymous"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1

[[menu.main]]
url = "/about"
name = "关于我"
weight = 3

[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4
